site_name: CriptonÃ³micon Rolo

theme:
  name: material
  language: es
  palette:

    primary: yellow
  font:
    text: Lexend Deca
  features:

    - search.suggest
    - navigation.tabs
    - header.autohide

copyright: Copyright &copy; 2023 Cryptonomicon Rolo

nav:
    - Home: index.md
    - Cinema y LecturağŸ¿ğŸ“š: audio_visual.md
    - PÃ¡ginas ÃštilesğŸŒ: paginas.md
    - Software ğŸ’½ : Software.md
    - Apple ğŸ’»: Apple.md

plugins:
  - search:
      lang:
        - es
        - en
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

